// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"helloadmin/internal/department"
	"helloadmin/internal/login_record"
	"helloadmin/internal/menu"
	"helloadmin/internal/repository"
	"helloadmin/internal/role"
	"helloadmin/internal/server"
	"helloadmin/internal/user"
	"helloadmin/pkg/app"
	"helloadmin/pkg/helper/sid"
	"helloadmin/pkg/jwt"
	"helloadmin/pkg/log"
	"helloadmin/pkg/server/http"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	sidSid := sid.NewSid()
	db := repository.NewDB(viperViper, logger)
	client := repository.NewRedis(viperViper)
	repositoryRepository := repository.NewRepository(db, client, logger)
	userRepository := user.NewUserRepository(repositoryRepository)
	userService := user.NewUserService(sidSid, jwtJWT, userRepository)
	loginRecordRepository := login_record.NewLoginRecordRepository(repositoryRepository)
	loginRecordService := login_record.NewService(loginRecordRepository)
	handler := user.NewHandler(logger, userService, loginRecordService)
	roleRepository := role.NewRoleRepository(repositoryRepository)
	roleService := role.NewRoleService(roleRepository)
	roleHandler := role.NewHandler(logger, roleService)
	menuRepository := menu.NewMenuRepository(repositoryRepository)
	service := menu.NewMenuService(menuRepository)
	menuHandler := menu.NewHandler(logger, service)
	deptRepository := department.NewDeptRepository(repositoryRepository)
	departmentService := department.NewDepartmentService(deptRepository)
	departmentHandler := department.NewHandler(logger, departmentService)
	login_recordHandler := login_record.NewHandler(logger, loginRecordService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, handler, roleHandler, menuHandler, departmentHandler, login_recordHandler)
	job := server.NewJob(logger)
	appApp := newApp(httpServer, job)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewRepository, repository.NewTransaction, role.NewRoleRepository, menu.NewMenuRepository, department.NewDeptRepository, login_record.NewLoginRecordRepository, user.NewUserRepository)

var serviceSet = wire.NewSet(role.NewRoleService, menu.NewMenuService, department.NewDepartmentService, login_record.NewService, user.NewUserService)

var handlerSet = wire.NewSet(role.NewHandler, menu.NewHandler, department.NewHandler, login_record.NewHandler, user.NewHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob, server.NewTask)

// build App
func newApp(httpServer *http.Server, job *server.Job) *app.App {
	return app.NewApp(app.WithServer(httpServer, job), app.WithName("hello-admin-server"))
}
