// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"helloadmin/internal/handler"
	"helloadmin/internal/repository"
	"helloadmin/internal/server"
	"helloadmin/internal/service"
	"helloadmin/pkg/app"
	"helloadmin/pkg/helper/sid"
	"helloadmin/pkg/jwt"
	"helloadmin/pkg/log"
	"helloadmin/pkg/server/http"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	client := repository.NewRedis(viperViper)
	repositoryRepository := repository.NewRepository(db, client, logger)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	roleRepository := repository.NewRoleRepository(repositoryRepository)
	roleService := service.NewRoleService(serviceService, roleRepository)
	roleHandler := handler.NewRoleHandler(handlerHandler, roleService)
	menuRepository := repository.NewMenuRepository(repositoryRepository)
	menuService := service.NewMenuService(serviceService, menuRepository)
	menuHandler := handler.NewMenuHandler(handlerHandler, menuService)
	departmentRepository := repository.NewDepartmentRepository(repositoryRepository)
	departmentService := service.NewDepartmentService(serviceService, departmentRepository)
	departmentHandler := handler.NewDepartmentHandler(handlerHandler, departmentService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, userHandler, roleHandler, menuHandler, departmentHandler)
	job := server.NewJob(logger)
	appApp := newApp(httpServer, job)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewRoleRepository, repository.NewMenuRepository, repository.NewDepartmentRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewRoleService, service.NewMenuService, service.NewDepartmentService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewRoleHandler, handler.NewMenuHandler, handler.NewDepartmentHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob, server.NewTask)

// build App
func newApp(httpServer *http.Server, job *server.Job) *app.App {
	return app.NewApp(app.WithServer(httpServer, job), app.WithName("demo-server"))
}
